package UMLClassDiagramLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Visibility extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Visibility() {
    super(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a2L, "Visibility", "r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247650");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Public_0 = new EnumerationDescriptor.MemberDescriptor("Public", "+", 0x61a8fafa698145a4L, "r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247652");
  private final EnumerationDescriptor.MemberDescriptor myMember_Private_0 = new EnumerationDescriptor.MemberDescriptor("Private", "-", 0x61a8fafa698145a7L, "r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247655");
  private final EnumerationDescriptor.MemberDescriptor myMember_Protected_0 = new EnumerationDescriptor.MemberDescriptor("Protected", "#", 0x61a8fafa698145a3L, "r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247651");
  private final EnumerationDescriptor.MemberDescriptor myMember_Package_0 = new EnumerationDescriptor.MemberDescriptor("Package", "~", 0x61a8fafa698145abL, "r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247659");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a2L, 0x61a8fafa698145a4L, 0x61a8fafa698145a7L, 0x61a8fafa698145a3L, 0x61a8fafa698145abL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Public_0, myMember_Private_0, myMember_Protected_0, myMember_Package_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Public":
        return myMember_Public_0;
      case "Private":
        return myMember_Private_0;
      case "Protected":
        return myMember_Protected_0;
      case "Package":
        return myMember_Package_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
