package UMLClassDiagramLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAggregation = createDescriptorForAggregation();
  /*package*/ final ConceptDescriptor myConceptAssociation = createDescriptorForAssociation();
  /*package*/ final ConceptDescriptor myConceptAssociationClass = createDescriptorForAssociationClass();
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptCardinality = createDescriptorForCardinality();
  /*package*/ final ConceptDescriptor myConceptClass = createDescriptorForClass();
  /*package*/ final ConceptDescriptor myConceptClassDiagramTemplate = createDescriptorForClassDiagramTemplate();
  /*package*/ final ConceptDescriptor myConceptClassReference = createDescriptorForClassReference();
  /*package*/ final ConceptDescriptor myConceptComposition = createDescriptorForComposition();
  /*package*/ final ConceptDescriptor myConceptInheritance = createDescriptorForInheritance();
  /*package*/ final ConceptDescriptor myConceptMethod = createDescriptorForMethod();
  /*package*/ final ConceptDescriptor myConceptMultiParameters = createDescriptorForMultiParameters();
  /*package*/ final ConceptDescriptor myConceptOne = createDescriptorForOne();
  /*package*/ final ConceptDescriptor myConceptParameter = createDescriptorForParameter();
  /*package*/ final ConceptDescriptor myConceptProperty = createDescriptorForProperty();
  /*package*/ final ConceptDescriptor myConceptRelation = createDescriptorForRelation();
  /*package*/ final ConceptDescriptor myConceptScope = createDescriptorForScope();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptTypeReference = createDescriptorForTypeReference();
  /*package*/ final EnumerationDescriptor myEnumerationVisibility = new EnumerationDescriptor_Visibility();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAggregation, myConceptAssociation, myConceptAssociationClass, myConceptAttribute, myConceptCardinality, myConceptClass, myConceptClassDiagramTemplate, myConceptClassReference, myConceptComposition, myConceptInheritance, myConceptMethod, myConceptMultiParameters, myConceptOne, myConceptParameter, myConceptProperty, myConceptRelation, myConceptScope, myConceptType, myConceptTypeReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Aggregation:
        return myConceptAggregation;
      case LanguageConceptSwitch.Association:
        return myConceptAssociation;
      case LanguageConceptSwitch.AssociationClass:
        return myConceptAssociationClass;
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.Cardinality:
        return myConceptCardinality;
      case LanguageConceptSwitch.Class:
        return myConceptClass;
      case LanguageConceptSwitch.ClassDiagramTemplate:
        return myConceptClassDiagramTemplate;
      case LanguageConceptSwitch.ClassReference:
        return myConceptClassReference;
      case LanguageConceptSwitch.Composition:
        return myConceptComposition;
      case LanguageConceptSwitch.Inheritance:
        return myConceptInheritance;
      case LanguageConceptSwitch.Method:
        return myConceptMethod;
      case LanguageConceptSwitch.MultiParameters:
        return myConceptMultiParameters;
      case LanguageConceptSwitch.One:
        return myConceptOne;
      case LanguageConceptSwitch.Parameter:
        return myConceptParameter;
      case LanguageConceptSwitch.Property:
        return myConceptProperty;
      case LanguageConceptSwitch.Relation:
        return myConceptRelation;
      case LanguageConceptSwitch.Scope:
        return myConceptScope;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.TypeReference:
        return myConceptTypeReference;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationVisibility);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAggregation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Aggregation", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806dd6L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Association", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e9L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185192406");
    b.version(2);
    b.alias("aggregation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Association", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e9L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Relation", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806d9fL);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247721");
    b.version(2);
    b.property("firstClassRole", 0x88ab51836c24410L).type(PrimitiveTypeId.STRING).origin("615503414692037648").done();
    b.property("secondClassRole", 0x88ab51836c24412L).type(PrimitiveTypeId.STRING).origin("615503414692037650").done();
    b.aggregate("firstClass", 0x61a8fafa69a68bf6L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699da096L).optional(false).ordered(true).multiple(false).origin("7037150371187690486").done();
    b.aggregate("secondClass", 0x61a8fafa69a68bf8L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699da096L).optional(false).ordered(true).multiple(false).origin("7037150371187690488").done();
    b.aggregate("firstCardinality", 0x61a8fafa69bde658L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814604L).optional(false).ordered(true).multiple(false).origin("7037150371189220952").done();
    b.aggregate("secondCardinality", 0x61a8fafa69bde65cL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814604L).optional(false).ordered(true).multiple(false).origin("7037150371189220956").done();
    b.alias("association");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociationClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "AssociationClass", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69a68bd9L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Association", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e9L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371187690457");
    b.version(2);
    b.aggregate("generatedClass", 0x61a8fafa69a7558bL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699bebd8L).optional(false).ordered(true).multiple(false).origin("7037150371187742091").done();
    b.alias("associationClass");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Attribute", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a0L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Property", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814569L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247648");
    b.version(2);
    b.alias("attribute");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCardinality() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Cardinality", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814604L);
    b.class_(false, true, false);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247748");
    b.version(2);
    b.alias("cardinality");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Class", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699bebd8L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371186994136");
    b.version(2);
    b.aggregate("attributes", 0x61a8fafa699bebddL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a0L).optional(true).ordered(true).multiple(true).origin("7037150371186994141").done();
    b.aggregate("methods", 0x61a8fafa699bebdfL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a1L).optional(true).ordered(true).multiple(true).origin("7037150371186994143").done();
    b.alias("class");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassDiagramTemplate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "ClassDiagramTemplate", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699f52ffL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371187217151");
    b.version(2);
    b.aggregate("classes", 0x61a8fafa69a0cbc8L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699bebd8L).optional(true).ordered(true).multiple(true).origin("7037150371187313608").done();
    b.aggregate("relations", 0x61a8fafa69a0cbccL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806d9fL).optional(true).ordered(true).multiple(true).origin("7037150371187313612").done();
    b.alias("classDiagram");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "ClassReference", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699da096L);
    b.class_(false, false, false);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371187105942");
    b.version(2);
    b.associate("target", 0x61a8fafa699da097L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699bebd8L).optional(false).origin("7037150371187105943").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComposition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Composition", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806dd5L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Association", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e9L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185192405");
    b.version(2);
    b.alias("composition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInheritance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Inheritance", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806dd4L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Relation", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806d9fL);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185192404");
    b.version(2);
    b.aggregate("baseClass", 0x61a8fafa69a75590L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699da096L).optional(false).ordered(true).multiple(false).origin("7037150371187742096").done();
    b.aggregate("derivedClasses", 0x61a8fafa69a75592L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa699da096L).optional(false).ordered(true).multiple(true).origin("7037150371187742098").done();
    b.alias("extension");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMethod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Method", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a1L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Property", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814569L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247649");
    b.version(2);
    b.aggregate("firstParameter", 0x61a8fafa69b82b39L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e8L).optional(true).ordered(true).multiple(false).origin("7037150371188845369").done();
    b.aggregate("multiParameters", 0x61a8fafa69baff8fL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69bbf168L).optional(true).ordered(true).multiple(true).origin("7037150371189030799").done();
    b.alias("method");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMultiParameters() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "MultiParameters", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69bbf168L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371189092712");
    b.version(2);
    b.aggregate("type", 0x61a8fafa69bceba6L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf379L).optional(false).ordered(true).multiple(false).origin("7037150371189156774").done();
    b.alias("multiParameter");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOne() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "One", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814655L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Cardinality", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814604L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247829");
    b.version(2);
    b.property("value", 0x61a8fafa69bde5b5L).type(PrimitiveTypeId.INTEGER).origin("7037150371189220789").done();
    b.alias("one");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Parameter", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145e8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247720");
    b.version(2);
    b.aggregate("type", 0x61a8fafa69b82a86L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf379L).optional(false).ordered(true).multiple(false).origin("7037150371188845190").done();
    b.alias("parameter");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Property", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814569L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247593");
    b.version(2);
    b.property("visibility", 0x61a8fafa6981b270L).type(MetaIdFactory.dataTypeId(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa698145a2L)).origin("7037150371185275504").done();
    b.aggregate("returnType", 0x61a8fafa698c8a85L).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf379L).optional(false).ordered(true).multiple(false).origin("7037150371185986181").done();
    b.alias("property");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Relation", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69806d9fL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185192351");
    b.version(2);
    b.alias("relation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScope() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Scope", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814657L);
    b.class_(false, false, false);
    b.super_("UMLClassDiagramLanguage.structure.Cardinality", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69814604L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371185247831");
    b.version(2);
    b.property("downValue", 0x61a8fafa69bde5f9L).type(PrimitiveTypeId.INTEGER).origin("7037150371189220857").done();
    b.property("upValue", 0x61a8fafa69bde5ffL).type(PrimitiveTypeId.INTEGER).origin("7037150371189220863").done();
    b.alias("scope");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "Type", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf376L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371187979126");
    b.version(2);
    b.alias("type");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UMLClassDiagramLanguage", "TypeReference", 0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf379L);
    b.class_(false, false, false);
    b.origin("r:c0caa512-eb02-40b0-8e8c-092fc63e2d4a(UMLClassDiagramLanguage.structure)/7037150371187979129");
    b.version(2);
    b.associate("target", 0x61a8fafa69b23ccbL).target(0x9f6af2edaadf44adL, 0xbf237f18f5a9a442L, 0x61a8fafa69aaf376L).optional(false).origin("7037150371188456651").done();
    return b.create();
  }
}
